### ISSUE TITLE
Propagate UCAN web3.storage keys in Livepeer services

### ISSUE THREAD

**Issue by leszko** [livepeer/catalyst#363]
Update Livepeer Infra configuration to propagate UCAN keys into the following services:
- catalyst: needs Private Key to interact with the w3s up API
- livepeer-api: needs DID (Public Key)

Here are the related configurations which injects Vault secrets as environment variables:
- [livepeer](https://github.com/livepeer/livepeer-infra/blob/cfd4d2dfff88c7fc9a011a11e6d3d587111e2f0e/values/livepeer.values.yaml#L57)
- [catalyst](https://github.com/livepeer/livepeer-infra/blob/cfd4d2dfff88c7fc9a011a11e6d3d587111e2f0e/values/catalyst.values.yaml#L75)

------------------------

**Acceptance criteria**
- Livepeer Infra configuration is updated with UCAN keys secrets taken from Vault
- Staging `catalyst` and `livepeer-api` pods are checked if the keys are visible there in their environment variables (can be checked with `kubectl describe pod <pod-name>`)
- Environment variables used: `LP_API_DID` and `CATALYST_UCAN_KEY`

**Comment by red-0ne** [comment]
Since catalyst-api is getting its variables as arguments. I propose to not have `CATALYST_UCAN_KEY` as env variable and let it be passed directly through catalyst-api args. If we need the value to be exposed as environment variable, then it should be assigned here I guess [livepeer-infra/values/catalyst.values.yaml](https://github.com/livepeer/livepeer-infra/blob/cfd4d2dfff88c7fc9a011a11e6d3d587111e2f0e/values/catalyst.values.yaml#L108)

**Comment by leszko** [comment]
> 

Yeah, agree, let's do the same what we do with other flags.

**Comment by leszko** [comment]
Reopening. Related Discord discussion: https://discord.com/channels/423160867534929930/1006190767510917202/1067432142876987492

**Comment by leszko** [comment]
The Studio part is done.

The Catalyst API part needs to wait until we introduce the related flag to Catalyst API
